飲食店一覧表示及び検索機能の追加
ayanodame/Rese-reservationsystem pull request #1
Opened 2022-01-11 03:45 UTC by ayanodame

・飲食店一覧表示の追加

・飲食店検索機能の追加

2022-01-11 05:40 UTC, mona0601 requested changes
とりあえず現状のコードをレビューしました。

2022-01-11 05:40 UTC, mona0601 commented on app/Http/Controllers/ShopController.php
> +        $results=Shop::where('name','LIKE',"%{$request->input_name}%")->where('area_id','LIKE',"%{$request->input_area}")->where('genre_id','LIKE',"%{$request->input_genre}")->get();
Controllerでビルダー使って検索するのではなく、ShopModel側に引数渡して検索させる機能を持たせて呼び出す方がよいですね。

2022-01-11 05:40 UTC, mona0601 commented on app/Http/Controllers/ShopController.php
> +        $results=Shop::where('name','LIKE',"%{$request->input_name}%")->where('area_id','LIKE',"%{$request->input_area}")->where('genre_id','LIKE',"%{$request->input_genre}")->get();
エリアとジャンルはIDなので `Like` ではなく `一致` ですかね。

2022-01-11 05:40 UTC, mona0601 commented on app/Http/Controllers/ShopController.php
> +        $results=Shop::where('name','LIKE',"%{$request->input_name}%")->where('area_id','LIKE',"%{$request->input_area}")->where('genre_id','LIKE',"%{$request->input_genre}")->get();
画面の検索項目は`name`ではなく`keyword`とかの方がよさそうですね。

2022-01-11 05:40 UTC, mona0601 commented on app/Http/Controllers/ShopController.php
> +        $keywords=[
`keywords` って何に使用していますか？

2022-01-11 07:48 UTC, ayanodame commented on app/Http/Controllers/ShopController.php
> +        $keywords=[
店名検索のinputタグで使用してます。

2022-01-11 08:56 UTC, ayanodame commented on app/Http/Controllers/ShopController.php
> +        $keywords=[
inputタグで必要かと思ってましたが、なしでもできたので、削除しました。

2022-01-16 15:03 UTC, ayanodame commented on app/Http/Controllers/ShopController.php
> +        $results=Shop::where('name','LIKE',"%{$request->input_name}%")->where('area_id','LIKE',"%{$request->input_area}")->where('genre_id','LIKE',"%{$request->input_genre}")->get();
keywordに変更しました。

2022-01-16 15:03 UTC, ayanodame commented on app/Http/Controllers/ShopController.php
> +        $results=Shop::where('name','LIKE',"%{$request->input_name}%")->where('area_id','LIKE',"%{$request->input_area}")->where('genre_id','LIKE',"%{$request->input_genre}")->get();
if文を使って、一致で検索できるように修正しました。

2022-01-25 09:20 UTC, mona0601 approved these changes
OKです。

2022-01-25 09:21 UTC, merged