ログイン機能を追加
ayanodame/Rese-reservationsystem pull request #3
Opened 2022-02-08 09:16 UTC by ayanodame

ログイン機能を追加

2022-02-08 09:28 UTC, mona0601 requested changes
修正お願いします。

2022-02-08 09:28 UTC, mona0601 commented on app/Http/Controllers/UserController.php
> +            $text = 'ログインに失敗しました。';
変数名を変えてください。

2022-02-08 09:28 UTC, mona0601 commented on app/Http/Controllers/UserController.php
> +        return view('login', ['text' => $text]);
`text` キーワードも変更してください。

2022-02-08 09:28 UTC, mona0601 commented on resources/views/login.blade.php
> +        <p class="message__login-error">{{$text}}</p>
`$text` 部分を修正してください。

2022-02-08 15:04 UTC, ayanodame commented on app/Http/Controllers/UserController.php
> +            $text = 'ログインに失敗しました。';
$errorMessageに変更しました。

2022-02-08 15:04 UTC, ayanodame commented on app/Http/Controllers/UserController.php
> +        return view('login', ['text' => $text]);
変数名及びキーワードをerrorMessageに変更しました。

2022-02-08 15:04 UTC, ayanodame commented on resources/views/login.blade.php
> +        <p class="message__login-error">{{$text}}</p>
$errorMessageに変更しました。

2022-02-09 01:48 UTC, mona0601 approved these changes
OKです！

2022-02-09 13:40 UTC, merged