店舗詳細画面及び予約登録機能の追加
ayanodame/Rese-reservationsystem pull request #4
Opened 2022-02-21 14:48 UTC by ayanodame

店舗詳細画面及び予約登録機能の追加

2022-02-22 09:34 UTC, mona0601 requested changes
レビュー指摘部分の修正お願いします。

2022-02-22 09:34 UTC, mona0601 commented on public/js/main.js
> +window.onload = function () {
main.js ではなく個別のjsを用意する方がよさそう

2022-02-22 09:34 UTC, mona0601 commented on public/js/main.js
> +    document.getElementById( "reserveCheckLength" ).innerHTML = $formObject.length;
reserveCheckLength というIDのエレメントがないので実行するとJavaScriptエラーが発生します。

2022-02-22 09:34 UTC, mona0601 commented on public/js/main.js
> +    var $formObject = document.getElementById( "reserveForm" );
日付、時刻、人数それぞれが変更された時には、変更された項目だけ反映するようにした方がよい

2022-02-24 10:05 UTC, ayanodame commented on public/js/main.js
> +window.onload = function () {
check.js　フォルダを作成しました。

2022-02-25 00:24 UTC, mona0601 requested changes
前回最後に指摘した以下の指摘に対応されていなかったので改めて指摘しました。
```
日付、時刻、人数それぞれが変更された時には、変更された項目だけ反映するようにした方がよい
```

2022-02-25 00:24 UTC, mona0601 commented on public/js/check.js
> +        getValue();
すべて `getValue()` を呼び出しているが、`inputDate`, `inputTime`, `inputNumber` の `onchange` ではそれぞれ対応する項目だけ設定すればいいですよね。
ですので  `getValue()` の function を用意する必要はなく、`getValue()` を呼び出している個所で `getValue()` 内に記載されているそれぞれの設定を書けばよいかと思いました。

2022-02-25 08:57 UTC, mona0601 approved these changes
OKです！

2022-02-25 14:34 UTC, merged