マイページ機能の追加
ayanodame/Rese-reservationsystem pull request #5
Opened 2022-03-07 09:25 UTC by ayanodame

・お気に入り店舗の登録及び削除機能の追加
・マイページに予約一覧&お気に入り店舗一覧の表示の追加
・予約削除機能の追加

2022-03-08 09:54 UTC, mona0601 requested changes
修正お願いします。

2022-03-08 09:54 UTC, mona0601 commented on app/Http/Controllers/LikeController.php
> +        $user = Auth::user();
不要かも？

2022-03-08 09:54 UTC, mona0601 commented on app/Models/Shop.php
> +    public function is_liked_by_auth_user()
メソッド名はスネークではなくキャメルで命名してください。

2022-03-08 09:54 UTC, mona0601 commented on app/Models/Shop.php
> +        $likers = array();
`likers` の変数名を変えてください。

2022-03-08 09:54 UTC, mona0601 commented on resources/views/index.blade.php
> +        <div class="card__like">
違いは `form`の`action名`と`いいね` の `画像名` だけなので共通化を考えてください。

2022-03-08 09:54 UTC, mona0601 commented on resources/views/mypage.blade.php
> +          @if($like->shop->is_liked_by_auth_user())
`いいね`じゃない情報は存在しないので、判定は不要です。

2022-03-08 09:54 UTC, mona0601 commented on app/Models/Shop.php
> +            array_push($likers, $like->user_id);
チェック用のユーザーIDの配列を用意する必要はなくて、ここで判定しましょう。

2022-03-09 08:33 UTC, ayanodame commented on app/Http/Controllers/LikeController.php
> +        $user = Auth::user();
削除しました。

2022-03-09 08:34 UTC, ayanodame commented on app/Models/Shop.php
> +    public function is_liked_by_auth_user()
キャメル記法に修正しました。

2022-03-09 08:34 UTC, ayanodame commented on app/Models/Shop.php
> +        $likers = array();
不要だったので、削除しました。

2022-03-09 08:35 UTC, ayanodame commented on resources/views/index.blade.php
> +        <div class="card__like">
いいね登録の時といいね解除時の変数を組み、共通化させました。

2022-03-09 08:35 UTC, ayanodame commented on resources/views/mypage.blade.php
> +          @if($like->shop->is_liked_by_auth_user())
削除しました。（いいね解除のフォームタグのみ残してます）

2022-03-09 08:35 UTC, ayanodame commented on app/Models/Shop.php
> +            array_push($likers, $like->user_id);
変更しました。

2022-03-09 23:12 UTC, mona0601 requested changes
指摘追加したので対応お願いします。

2022-03-09 23:12 UTC, mona0601 commented on app/Models/Shop.php
> +    public function LikedByAuthUser()
先頭は英小文字で合わせてください。

2022-03-09 23:12 UTC, mona0601 commented on app/Models/Shop.php
> +            } else {
forで繰り返しているのに `else` で `return` すると最初の１回目で`for`抜けちゃいますよね？

2022-03-09 23:12 UTC, mona0601 commented on resources/views/index.blade.php
> +        @if($shop->LikedByAuthUser())
ここの `if` も `<?php` に含めたら `<?php` だけで記述できそうですね。

2022-03-10 09:14 UTC, ayanodame commented on app/Models/Shop.php
> +    public function LikedByAuthUser()
小文字に変更しました。

2022-03-10 09:15 UTC, ayanodame commented on app/Models/Shop.php
> +            } else {
elseから後ろは削除しました。

2022-03-10 09:16 UTC, ayanodame commented on resources/views/index.blade.php
> +        @if($shop->LikedByAuthUser())
php構文にまとめました。

2022-03-10 23:16 UTC, mona0601 requested changes
あと１点だけです。
軽微な修正なので、修正終わったらマージしちゃってOKです。

2022-03-10 23:16 UTC, mona0601 commented on app/Models/Shop.php
>      }
`foreach` を抜けた場合は認証ユーザーの `like` 情報がなかったという事なので、`return false;` 必要ですよね。

2022-03-10 23:16 UTC, mona0601 approved these changes

2022-03-11 09:09 UTC, merged